/*
 * Copyright (c) 2026 Eyal Tal. All rights reserved. Proprietary and confidential. Unauthorized copying of this file is strictly prohibited.
 *
 *
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { DoctorCheck, DoctorResult } from "../types.ts";

function readJson<T>(filePath: string): T | null {
  try {
    if (!fs.existsSync(filePath)) return null;
    return JSON.parse(fs.readFileSync(filePath, "utf-8")) as T;
  } catch {
    return null;
  }
}

function readEnvVar(key: string): string | null {
  if (process.env[key]) return process.env[key];
  try {
    const envPath = path.resolve(".env");
    if (!fs.existsSync(envPath)) return null;
    const content = fs.readFileSync(envPath, "utf-8");
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      const k = trimmed.slice(0, eqIdx).trim();
      if (k === key) {
        let val = trimmed.slice(eqIdx + 1).trim();
        if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
          val = val.slice(1, -1);
        }
        return val || null;
      }
    }
  } catch {
    return null;
  }
  return null;
}

const pipeScriptsExist: DoctorCheck = {
  id: "PIPE-001",
  category: "Pipeline Health",
  run(): DoctorResult {
    const requiredScripts = [
      "scripts/pipeline/import-data.ts",
      "scripts/pipeline/update-site.ts",
      "scripts/pipeline/image-scanner.ts",
      "scripts/pipeline/image-resolver.ts",
      "scripts/pipeline/constants.ts",
      "scripts/pipeline/validators.ts",
      "scripts/pipeline/logger.ts",
      "scripts/pipeline/generators.ts",
    ];
    const missing: string[] = [];
    for (const s of requiredScripts) {
      if (!fs.existsSync(path.resolve(s))) {
        missing.push(s);
      }
    }
    if (missing.length === 0) {
      return { id: "PIPE-001", category: "Pipeline Health", status: "PASS", summary: "All required pipeline scripts exist." };
    }
    return {
      id: "PIPE-001", category: "Pipeline Health", status: "FAIL",
      summary: missing.length + " pipeline script(s) missing.",
      details: missing,
      recommendation: "Restore the missing pipeline components from version control.",
    };
  },
};

const pipeGeneratedData: DoctorCheck = {
  id: "PIPE-002",
  category: "Pipeline Health",
  run(): DoctorResult {
    const files = [
      { file: "src/content/products.json", name: "products" },
      { file: "src/content/collections.json", name: "collections" },
      { file: "src/content/forms.json", name: "forms" },
    ];
    const issues: string[] = [];
    for (const { file, name } of files) {
      const fullPath = path.resolve(file);
      if (!fs.existsSync(fullPath)) {
        issues.push(name + ".json is missing.");
        continue;
      }
      const parsed = readJson<Record<string, unknown>>(fullPath);
      if (!parsed) {
        issues.push(name + ".json is not valid JSON.");
        continue;
      }
      const meta = parsed._metadata as Record<string, unknown> | undefined;
      if (!meta || meta.generated !== true) {
        issues.push(name + ".json was not generated by the pipeline.");
        continue;
      }
      if (!Array.isArray(parsed.data) || parsed.data.length === 0) {
        issues.push(name + ".json has an empty data array.");
      }
    }
    if (issues.length === 0) {
      return { id: "PIPE-002", category: "Pipeline Health", status: "PASS", summary: "All generated data files are available and valid." };
    }
    return {
      id: "PIPE-002", category: "Pipeline Health", status: "FAIL",
      summary: "Generated content data issues found.",
      details: issues,
      recommendation: "Run the data import pipeline to regenerate data.",
    };
  },
};

const pipeConfig: DoctorCheck = {
  id: "PIPE-003",
  category: "Pipeline Health",
  run(): DoctorResult {
    const drive = ["GOOGLE_DRIVE_ROOT_FOLDER_ID", "GOOGLE_SERVICE_ACCOUNT_EMAIL", "GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY"];
    const sheets = ["INVENTORY_GOOGLE_SHEETS_ID"];
    const submission = ["PUBLIC_SUBMISSION_ENDPOINT"];
    const missingDrive = drive.filter((k) => !readEnvVar(k));
    const missingSheets = sheets.filter((k) => !readEnvVar(k));
    const missingSubmission = submission.filter((k) => !readEnvVar(k));
    const sheetsEnabled = readEnvVar("SHEETS_ENABLED") === "true";
    const warnings: string[] = [];
    if (missingDrive.length > 0) {
      warnings.push("Google Drive configuration incomplete: " + missingDrive.join(", "));
    }
    if (sheetsEnabled && missingSheets.length > 0) {
      warnings.push("Google Sheets configuration incomplete: " + missingSheets.join(", "));
    }
    if (missingSubmission.length > 0) {
      warnings.push("Submission endpoint configuration missing.");
    }
    if (warnings.length === 0) {
      return { id: "PIPE-003", category: "Pipeline Health", status: "PASS", summary: "All pipeline integrations are configured." };
    }
    return {
      id: "PIPE-003", category: "Pipeline Health", status: "WARN",
      summary: warnings.length + " pipeline configuration issue(s).",
      details: warnings,
      recommendation: "Configure missing integration settings in .env.",
    };
  },
};

const pipeOutputConsistency: DoctorCheck = {
  id: "PIPE-004",
  category: "Pipeline Health",
  run(): DoctorResult {
    const products = readJson<{ data: Record<string, unknown>[]; _metadata: Record<string, unknown> }>(path.resolve("src/content/products.json"));
    const collections = readJson<{ data: Record<string, unknown>[] }>(path.resolve("src/content/collections.json"));
    const forms = readJson<{ data: Record<string, unknown>[] }>(path.resolve("src/content/forms.json"));
    const issues: string[] = [];
    if (!products || !collections || !forms) {
      return { id: "PIPE-004", category: "Pipeline Health", status: "FAIL", summary: "Cannot verify consistency; data files missing.", recommendation: "Run the data import pipeline." };
    }
    if (products.data.length === 0) {
      issues.push("Products dataset is empty.");
    }
    if (collections.data.length === 0) {
      issues.push("Collections dataset is empty.");
    }
    if (forms.data.length === 0) {
      issues.push("Forms dataset is empty.");
    }
    const validFormIds = new Set(forms.data.map((f) => String(f.id || "")));
    for (const p of products.data) {
      const formId = p.formId as string | undefined;
      if (formId && !validFormIds.has(formId)) {
        issues.push("Product " + p.id + " references unknown form: " + formId);
      }
    }
    const businessAreas = new Set(products.data.map((p) => String(p.businessArea || "")));
    for (const c of collections.data) {
      const ba = c.businessArea as string | undefined;
      if (ba && ba !== "null" && !businessAreas.has(ba)) {
        issues.push("Collection " + c.id + " has businessArea not found in any product: " + ba);
      }
    }
    if (issues.length === 0) {
      return { id: "PIPE-004", category: "Pipeline Health", status: "PASS", summary: "Pipeline output is consistent across all datasets." };
    }
    return {
      id: "PIPE-004", category: "Pipeline Health", status: "WARN",
      summary: issues.length + " consistency issue(s) found.",
      details: issues,
      recommendation: "Review cross-dataset references and re-run the pipeline.",
    };
  },
};

const pipeBuildReadiness: DoctorCheck = {
  id: "PIPE-005",
  category: "Pipeline Health",
  run(): DoctorResult {
    const checks: { label: string; ok: boolean }[] = [
      { label: "Astro config", ok: fs.existsSync(path.resolve("astro.config.mjs")) },
      { label: "Page routes", ok: fs.existsSync(path.resolve("src/pages")) },
      { label: "Layouts", ok: fs.existsSync(path.resolve("src/layouts")) },
      { label: "Components", ok: fs.existsSync(path.resolve("src/components")) },
      { label: "Global styles", ok: fs.existsSync(path.resolve("src/styles/global.css")) },
      { label: "Static public dir", ok: fs.existsSync(path.resolve("public")) },
      { label: "Generated products data", ok: fs.existsSync(path.resolve("src/content/products.json")) },
      { label: "Generated collections data", ok: fs.existsSync(path.resolve("src/content/collections.json")) },
    ];
    const failed = checks.filter((c) => !c.ok);
    if (failed.length === 0) {
      return { id: "PIPE-005", category: "Pipeline Health", status: "PASS", summary: "All required build inputs are available." };
    }
    return {
      id: "PIPE-005", category: "Pipeline Health", status: "FAIL",
      summary: failed.length + " build input(s) missing.",
      details: failed.map((f) => "Missing: " + f.label),
      recommendation: "Restore missing build inputs from version control.",
    };
  },
};

const pipelineChecks: DoctorCheck[] = [pipeScriptsExist, pipeGeneratedData, pipeConfig, pipeOutputConsistency, pipeBuildReadiness];

export default pipelineChecks;